### PR TITLE
[WIP] Add scroll support.

### PR DESCRIPTION
**Pull request by SkyzohKey**
We should be able to scroll the Sheet in whatever direction we want, so added a ScrolledView and a Viewport, maybe it would be better to handle that inside the Sheet widget, allowing us to keep the columns/rows header fixed will the sheet scrolls. :)

### CODE REVIEW

**Comment by Bat41** [comment]
Great! I tried to do it using the `Scrollable` interface, but it didn't worked. Thanks for your help. :smile:

**Comment by Bat41** [comment]
Tell me if you want me to merge it now, or if you want to add thinks.

**Comment by SkyzohKey** [comment]
I don't know if this should be merged x')

**Comment by Bat41** [comment]
If it works, I think i'll merge it now. We can always improve it later.

**Comment by Bat41** [comment]
Does it work on your computer? Because I just tested and I can scroll. :sob:

**Comment by SkyzohKey** [comment]
Yep it work if the Sheet is bigger than the Viewport ^^. Maybe set_size_request(2000, 2000); on the sheet ? c:

**Comment by Bat41** [comment]
Ah, yes it works with the size request! Thanks. :slightly_smiling_face:

**Pull request merged**
